(()=>{'use strict';
const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let playing=!reduced.matches,visible=true,t=0,last=0,job=0,w=600,h=310;
const jobs=[{aisle:'A',x:7,z:4,id:'DEMO-101',date:'2025-01-04'},{aisle:'B',x:3,z:6,id:'DEMO-102',date:'2025-01-06'},{aisle:'A',x:5,z:2,id:'DEMO-103',date:'2025-01-09'},{aisle:'B',x:8,z:3,id:'DEMO-104',date:'2025-01-11'}];
function project(x,y,z){let s=Math.min(w/25,h/17);return [w*.51+(x-y)*s,h*.48+(x+y)*s*.37-z*s*.83]}
function face(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>{const q=project(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.65;ctx.stroke()}}
function box(x,y,z,a,b,c,color){face([[x,y,z+c],[x+a,y,z+c],[x+a,y+b,z+c],[x,y+b,z+c]],color[0]);face([[x,y+b,z],[x+a,y+b,z],[x+a,y+b,z+c],[x,y+b,z+c]],color[1]);face([[x+a,y,z],[x+a,y+b,z],[x+a,y+b,z+c],[x+a,y,z+c]],color[2])}
const steel=['#9aa5ae','#7f8d98','#b0b3b5'],pallet=['#caa38d','#b58468','#d4b6a4'],carton=['#ebd6c9','#d2af9a','#e1c5b4'];
function rack(y){for(let level=0;level<7;level++){for(let col=0;col<10;col++){if((col*3+level*7+Math.round(y))%11!==0){box(col*.94,y,level*.94+.1,.72,.65,.09,pallet);box(col*.94+.07,y+.05,level*.94+.2,.57,.53,.59,carton)}}box(-.12,y+.7,level*.94,9.6,.08,.07,steel)}for(let col=0;col<=10;col++)box(col*.94-.1,y+.7,0,.065,.08,6.8,steel)}
function crane(y,isA){const j=jobs[job%jobs.length],cycle=Math.max(0,(t-1800)/6200),phase=Math.min(1,cycle),active=(j.aisle==='A')===isA;let x=active?j.x*.94:((j.x+3)%9)*.94,z=active?j.z*.94:2.3;if(active){if(phase<.35){x=.25+(x-.25)*ease(phase/.35);z=.25+(z-.25)*ease(phase/.35)}else if(phase>.65){x=x+(.25-x)*ease((phase-.65)/.35);z=z+(.25-z)*ease((phase-.65)/.35)}}const c=isA?['#6e8ca5','#3d6a8f','#436c8d']:['#dea483','#b56333','#d18152'];box(x,y,0,.42,.7,.28,c);box(x+.10,y+.20,.2,.22,.24,7.1,c);box(x-.12,y-.05,z,.7,.9,.14,steel);if(!active||phase>=.48)box(x-.04,y+.04,z+.14,.5,.65,.55,carton);const p=project(x+.2,y+.3,7.6);ctx.fillStyle=isA?'#3d6a8f':'#b56333';ctx.font='bold 11px system-ui';ctx.fillText(isA?'A':'B',p[0],p[1]);}
function ease(v){v=Math.max(0,Math.min(1,v));return v*v*(3-2*v)}
function draw(){ctx.clearRect(0,0,w,h);face([[-1,-1,0],[10,-1,0],[10,9,0],[-1,9,0]],'#dfe1e2','#cbcdcf');for(let y of [2,6])box(-.5,y,-.02,10.5,.09,.05,steel);ctx.globalAlpha=.65;rack(0);rack(3.2);rack(7.2);ctx.globalAlpha=1;crane(2,true);crane(6,false);box(-.8,1.7,0,.6,6,.35,['#c4c6c8','#83909b','#a4aeb7']);}
let prevPhase='';function update(){const j=jobs[job%jobs.length],slot=`${j.aisle}-${String(j.x).padStart(2,'0')}-${String(j.z).padStart(2,'0')}`;document.getElementById('location').textContent=slot;document.getElementById('fifo').textContent=j.date.slice(5)+' · '+j.id;document.getElementById('job').textContent=j.id+' · '+slot;document.querySelectorAll('[data-stage]').forEach(el=>{const stage=t<600?0:t<1200?1:t<1800?2:3;el.classList.toggle('active',Number(el.dataset.stage)===stage);el.classList.toggle('done',Number(el.dataset.stage)<stage)});const phase=t<3970?'Moving to slot':t<5830?'Retrieving oldest eligible pallet':'Returning to transfer point';if(phase!==prevPhase){document.getElementById('phase').textContent=phase;document.getElementById('task').textContent=t<2800?'X / Z positioning':t<5200?'FIFO retrieval':'Transfer → ERP status';prevPhase=phase}window.translateDemo?.()}
function size(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function tick(now){if(playing&&visible&&!document.hidden){t+=Math.min(now-last,50);if(t>=8000){t=0;job++}update();draw()}last=now;requestAnimationFrame(tick)}
const pause=document.getElementById('pause');function label(){pause.textContent=playing?'Pause motion':'Play motion';pause.setAttribute('aria-pressed',String(!playing));window.translateDemo?.()}pause.onclick=()=>{playing=!playing;label()};document.getElementById('next').onclick=()=>{job++;t=playing?0:3600;prevPhase='';update();draw()};reduced.addEventListener('change',()=>{playing=!reduced.matches;label()});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting}).observe(canvas);new ResizeObserver(size).observe(canvas);label();update();size();requestAnimationFrame(tick);
})();
